name: Distribution

on:
  push:
    branches:
      - master

jobs:
  copr-build:
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    name: Build latest RPM
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ secrets.COPR_CONF }}" > copr_conf
    - name: Build the package
      run: |
        docker run --name package-build -v $PWD:/code:Z registry.fedoraproject.org/fedora:32 /bin/bash -c "
          dnf install -y git make rpmdevtools copr-cli rpm-build python3
          cd
          git clone https://github.com/Nitrate/Nitrate
          cd Nitrate
          git checkout develop
          IFS='-' read version commits last_commit <<< \$(git describe)
          rpmdev-bumpspec -n \"\$(cat VERSION.txt)-\$commits.\$last_commit%{?dist}\" -c 'Rebuilt for latest' -u 'autobuild <autobuild@localhost>' -D python-nitrate-tcms.spec
          make tarball srpm
          copr-cli --conf /code/copr_conf build cqi/python-nitrate-tcms-testing dist/python-nitrate-tcms-*.src.rpm
        "

  build-image:
    name: Build latest RPM
    needs: copr-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the image
      run: |
        docker build -t nitrate:test .
