name: Demo Workflow

on:
  push:
    branches:
      - master

jobs:
  copr-build:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    name: Try something
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install git
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - run: |
        IFS='-' read version commits last_commit <<< $(git describe)
        echo "NITRATE_VERSION=${version}" >> $GITHUB_ENV
        echo "NITRATE_COMMITS=${commits}" >> $GITHUB_ENV
        echo "NITRATE_LAST_COMMIT=${last_commit}" >> $GITHUB_ENV
    - run: |
        echo "version: ${NITRATE_VERSION}; commits: $NITRATE_COMMITS; last_commit: ${NITRATE_LAST_COMMIT}%{?dist}"
