name: Distribution

on: push

jobs:
  pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    # - name: Check if current version package is available in PyPI
    #   run: |
    #     python -m pip download --quiet --no-binary :all: --no-deps "nitrate-tcms==$RELEASE_VERSION" && :
    - name: Publish to PyPI
      run: echo push tag $RELEASE_VERSION
